Site/Models/Component/SiteMenuOptionsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Site.Interfaces;
using Site.Models;
using Site.Repositorios;

namespace HDProjectWeb.Models.Detalles
{
    [ViewComponent(Name = "SiteMenuOptions")]
    public class SiteMenuOptionsViewComponent : ViewComponent
	{
        private readonly ISiteMenuOptionsRepository _repository;
        public SiteMenuOptionsViewComponent(ISiteMenuOptionsRepository repository)
        {
            _repository = repository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {  
            var products = await _repository.ListaMenuOpciones();
            return View(products);
        }
    }
}

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title >@ViewData["Title"] - Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Site.styles.css" asp-append-version="true" />
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img class="ms-5" src="data:image/jpg;base64,@ViewBag.File_Base64" width="100" height="60" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewBag.Company_Nombre</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    @await Component.InvokeAsync("SiteMenuOptions");
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<footer class="border-top footer text-muted">  
      <div id="footer-page">
          <table>
              <tr>
                <td>
                    <div class="d-flex flex-row">
                   <img class="ms-5" src="data:image/jpg;base64,@ViewBag.File_Base64" width="100" height="60" />
                   <p class="ms-1">@ViewBag.Company_Nombre © 2023 </p> 
                   
                   </div>
                </td>
                <td><a href="">Inicio</a></td>
                <td><a href="">Politica de Privacidad</a></td>
              </tr>
              <tr>
                <td><p>Todos los derechos reservados.</p></td>
                <td><a href="">Servicios</a></td>
            </tr>
            <tr>
                <td>5</td>
                <td>6</td>
            </tr>
          </table>
     </div>
</footer>
</html>